# Generated by Django 4.1.7 on 2023-04-24 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('modelo', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('referencia', models.CharField(max_length=150)),
                ('FKidEquipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeustubularSL_app.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('DNI', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('FKidProcesp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeustubularSL_app.proceso')),
            ],
        ),
    ]
