# Generated by Django 4.1.7 on 2023-04-29 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeustubularSL_app', '0003_proceso_fechafin_proceso_fechaini'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='fechaAdquisicion',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='equipo',
            name='fechaInstalacion',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
