# Generated by Django 4.1.7 on 2023-04-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeustubularSL_app', '0004_equipo_fechaadquisicion_equipo_fechainstalacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='codigoProceso',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proceso',
            name='ordenFabricacion',
            field=models.IntegerField(default=0),
        ),
    ]
