# Generated by Django 4.1.7 on 2023-05-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeustubularSL_app', '0007_empleado_telfono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='telfono',
            field=models.CharField(default=0, max_length=9),
        ),
    ]
