# Generated by Django 4.1.7 on 2023-05-20 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeustubularSL_app', '0008_alter_empleado_telfono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='telfono',
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fechaAdquisicion',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fechaInstalacion',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='fechaFin',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='fechaIni',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
