# Generated by Django 4.1.7 on 2023-05-20 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeustubularSL_app', '0010_alter_equipo_fechaadquisicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='fechaIni',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
