# Generated by Django 4.1.7 on 2023-05-20 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeustubularSL_app', '0012_alter_equipo_fechaadquisicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='fechaAdquisicion',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fechaInstalacion',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='fechaFin',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='fechaIni',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
